---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 89.169.161.216
    jenkins-agent-01:
      ansible_host: 89.169.165.45
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: root